server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 43.200.132.48
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/speensta/config

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh